require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set
local neogit = require "neogit"
local snacks = require "snacks"

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")

map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")

-- Tmux Navigator keymaps
map("n", "<c-h>", "<cmd> TmuxNavigateLeft<cr>")
map("n", "<c-j>", "<cmd> TmuxNavigateDown<cr>")
map("n", "<c-k>", "<cmd> TmuxNavigateUp<cr>")
map("n", "<c-l>", "<cmd> TmuxNavigateRight<cr>")
map("n", "<c-\\>", "<cmd> TmuxNavigatePrevious<cr>")

-- Neogit keymaps
map("n", "<leader>gs", neogit.open, { desc = "Neogit status" })
map("n", "<leader>gc", "<cmd> Neogit commit<cr>", { desc = "Neogit commit" })
map("n", "<leader>gp", "<cmd> Neogit pull<cr>", { desc = "Neogit pull" })
map("n", "<leader>gP", "<cmd> Neogit push<cr>", { desc = "Neogit push" })

-- Telescope keymaps
-- map("n", "<leader>gb", "<cmd> Telescope git_branches<cr>", { desc = "Telescope branches" })

-- Undotree keymaps
map("n", "<leader>ut", vim.cmd.UndotreeToggle, { desc = "Toggle Undotree" })

-- Gitsigns keymaps
map("n", "<leader>gh", "<cmd> Gitsigns preview_hunk<cr>", { desc = "Preview hunk" })
map("n", "<leader>gG", "<cmd> Gitsigns toggle_current_line_blame<cr>", { desc = "Toggle current line blame" })

-- Snacks keymaps
map("n", "<leader>un", function()
  snacks.notifier.hide()
end, { desc = "Dismiss Notifications" })
map("n", "<leader>ss", function()
  snacks.picker.lsp_symbols()
end, { desc = "LSP Symbols" })
map("n", "<leader>sS", function()
  snacks.picker.lsp_workspace_symbols()
end, { desc = "LSP Workspace Symbols" })
map("n", "<leader>sc", function()
  snacks.picker.command_history()
end, { desc = "Command History" })
map("n", "<leader>sC", function()
  snacks.picker.commands()
end, { desc = "Commands" })
map("n", "<leader>sd", function()
  snacks.picker.diagnostics()
end, { desc = "Diagnostics" })
map("n", "<leader>sD", function()
  snacks.picker.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
map("n", "<leader>si", function()
  snacks.picker.icons()
end, { desc = "Icons" })
map("n", "<leader>sM", function()
  snacks.picker.man()
end, { desc = "Man Pages" })
map("n", "<leader>sq", function()
  snacks.picker.qflist()
end, { desc = "Quickfix List" })
map("n", "<leader>sb", function()
  snacks.picker.lines()
end, { desc = "Buffer Lines" })
map("n", "<leader>sB", function()
  snacks.picker.grep_buffers()
end, { desc = "Grep Open Buffers" })
map("n", "<leader>fw", function()
  snacks.picker.grep()
end, { desc = "Grep" })
map({ "n", "x" }, "<leader>sw", function()
  snacks.picker.grep_word()
end, { desc = "Visual selection or word" })
map("n", "<leader>fo", function()
  snacks.picker.recent()
end, { desc = "Recent" })
map("n", "<leader>ff", function()
  snacks.picker.files()
end, { desc = "Find Files" })
map("n", "<leader><space>", function()
  snacks.picker.smart()
end, { desc = "Smart Find Files" })
map("n", "<leader>fa", function()
  snacks.picker.smart()
end, { desc = "Smart Find Files" })
map("n", "<leader>fb", function()
  snacks.picker.buffers()
end, { desc = "Buffers" })
map("n", "<leader>gb", function()
  snacks.picker.git_branches()
end, { desc = "Git Branches" })
map("n", "<leader>fh", function()
  snacks.picker.help()
end, { desc = "Help Pages" })
map("n", '<leader>s"', function()
  snacks.picker.registers()
end, { desc = "Registers" })
map("n", "<leader>s/", function()
  snacks.picker.search_history()
end, { desc = "Search History" })
map("n", "<leader>sa", function()
  snacks.picker.autocmds()
end, { desc = "Autocmds" })
map("n", "<leader>gt", function()
  snacks.picker.git_status()
end, { desc = "Git Status" })
map("n", "<leader>uh", function()
  snacks.picker.notifications()
end, { desc = "Notification History" })
